apiVersion: v1
kind: Service
namespace: argocd-test
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: argocd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
